kind: Service
apiVersion: v1
metadata:
  name: socryx-topled
  namespace: ingress-nginx
spec:
  ports:
    - name: urbit-https
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 0
---
kind: Endpoints
apiVersion: v1
metadata:
  name: socryx-topled
  namespace: ingress-nginx
subsets:
- addresses:
  - ip: 10.17.12.146
  ports:
  - port: 443
    name: urbit-https
