apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: example-clusterissuer
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: example-clusterissuer-account-key
    solvers:
    - http01:
       ingress:
         serviceType: ClusterIP
