---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: any-old-app-devl
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./flux-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: any-old-app-main
    namespace: devl
  validation: client
