---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: any-old-app
  namespace: devl
spec:
  interval: 1m0s
  path: ./flux
  prune: true
  sourceRef:
    kind: GitRepository
    name: any-old-app-main
  validation: client
  postBuild:
    substitute:
      GIT_SHA: ''
    substituteFrom:
      - kind: ConfigMap
        name: any-old-app-version
