---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  dependsOn:
    - name: flux-system
  interval: 10m0s
  path: ./moo-cluster/cluster-issuers
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
