apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 5m
  path: "./manifests/insecure-release/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: metrics-server
  validation: client
  healthChecks:
    - kind: Deployment
      name: metrics-server
      namespace: kube-system
  timeout: 80s
