apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hephy
  namespace: deis
spec:
  interval: 5m
  chart:
    spec:
      chart: workflow
      version: '2.22.3'
      sourceRef:
        kind: HelmRepository
        name: hephy
        namespace: flux-system
      interval: 1m
  values: {}
