apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkinsci
  namespace: flux-system
spec:
  interval: 5m
  releaseName: jenkins
  targetNamespace: jenkins
  storageNamespace: jenkins
  chart:
    spec:
      chart: ./charts/jenkins
      version: '^3.5.10'
      sourceRef:
        kind: GitRepository
        name: jenkins-charts
        namespace: flux-system
      interval: 40m
  values:
    controller:
      image: kingdonb/jenkins # {"$imagepolicy": "flux-system:jenkins:image"}
      tag: lts-be39f1e8-1628868492 # {"$imagepolicy": "flux-system:jenkins:tag"}
      installPlugins: false
      imagePullPolicy: IfNotPresent
      ingress:
        enabled: true
        apiVersion: networking.k8s.io/v1
        hostName: jenkins.hephy.pro
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          kubernetes.io/ingress.class: nginx
        tls:
          - secretName: jenkins.hephy.pro
            hosts:
              - jenkins.hephy.pro
      JCasC:
        defaultConfig: false
        configScripts:
          github-oauth: |
            jenkins:
              securityRealm:
                github:
                  githubWebUri: "https://github.com"
                  githubApiUri: "https://api.github.com"
                  clientID: "b4424bc483948a93d4d3"
                  clientSecret: "${jenkins-github-secret-token}"
                  oauthScopes: "read:org,user:email"

          crumb-issuer: |
            jenkins:
              crumbIssuer:
                standard:
                  excludeClientIPFromCrumb: true

          remoting-security: |
            jenkins:
              remotingSecurity:
                enabled: true

      additionalExistingSecrets:
        - name: jenkins-github
          keyName: secret-token
