apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkinsci
  namespace: flux-system
spec:
  interval: 5m
  releaseName: jenkins
  targetNamespace: jenkins
  storageNamespace: jenkins
  chart:
    spec:
      chart: jenkins
      version: '^3.5.10'
      sourceRef:
        kind: HelmRepository
        name: jenkinsci
        namespace: flux-system
      interval: 40m
  values:
    controller:
      image: kingdonb/jenkins
      tag: lts
      installPlugins: false
      imagePullPolicy: IfNotPresent
      ingress:
        enabled: true
        apiVersion: networking.k8s.io/v1
        hostName: jenkins.hephy.pro
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          kubernetes.io/ingress.class: nginx
        tls:
        - secretName: jenkins.hephy.pro
          hosts:
            - jenkins.hephy.pro
