apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helmrepo.yaml
- helmrelease.yaml
- namespace.yaml
- apps-jenkins-automation.yaml
- kingdonb-jenkins-registry.yaml
- jenkins-policy.yaml
- flux-system-rw-gitrepo.yaml
#- jenkins-charts-gitrepo.yaml
