data: ENC[AES256_GCM,data:MyYWswqp7v/I1f/FZXH2EA==,iv:KN6Jf5sPm8HapSc0oxkOy4WRIgXqVQbkCrcTpqAb3lE=,tag:8pOFrxP4ddIahnE2MZtT0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-03-29T13:00:43Z"
    mac: ENC[AES256_GCM,data:+V2AGE3XEEWCcEJltxhqF8fysfN9vn1ZwmIjKMuQiwz4NW1bRXr1MUQ3Plyit7ecLvsScRWfgHzkzTYBUbnzPvDxwKIiwdug3qHhc13Q3gVT8JcYhTC37Sh4YlF4Aj/sCgK7+VsAXJVlv1px4H8nUH7v19jojOqKI63TRL63La8=,iv:ZkVa9OcChkivPdwOfD5WJs1jX6H2LUJSaawl6I2qT20=,tag:fRQ8C4dk/W5qfl7TCAaTBg==,type:str]
    pgp:
        - created_at: "2021-03-29T13:00:42Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA06rSFOpPqRMARAAnhL+QgPhga7FyBQmLGL90kdiU1cqCuFRPOND8BWW+Oje
            7iBZ9ZKnOnYgeCF/tmBGULY0yd3b8iQz4bUnauZ5GLp9UbcAoUuDDLYZzIwvcNut
            K16GFBaanAX4HQa4A9yxVr3xicONaq3JYJWpz7FdB5HqieTt2VwVKzImo65+PeyJ
            swdhKjOlxAwmOtUtmh74BafR/I/NGPFeZ9bhtg2uRjO0udQ25YDtM7/LSDuZV4Fa
            eBF3hEcH7l6M8Z6eQd5zt9ZRatalLs0t56wnTUO+E3NgbXvWHcTXYqPLRH6thEH6
            1HTtBnkwhHPq1adhKy8Y9GLqMJ86BZlsXDROxUw7sSND8Jb6YwJrY9gdTe+kQaOU
            1wioFOaiA7gWs3JQ56KMAJR5IkZMgu4GYfKST438frPw2ZzU6DbFZ007bvuOCUM9
            nPZOq/MB2uNXN1bOICzCUgVNNME059uOICGa1MbqdUFXYaJH45bwl+2NZDViXuGV
            WTDgjv0qSwMw32HVvsHE2kqMPzVpTKvjZoRq4CA2lZp+n0dVKZL5Z6qozQnYjRl6
            yiWtTx8k5plSLAQXTvEzarkZcOGTvCvWo75gstt3lb9SOebPqNvlSX4XGGK3CKUN
            FOb2OiR4+mSnEnfJTMdu7lPC/J9U8ELDFpfGpUd77EhsE2QnD+3cPQTdsSWsHGXS
            XgFU73SPUekKWhxr4AyOgniWeMiBAyqD+/KyLFiFuVaMtgAU9wmtZc1xe7wf/5UG
            jRsT7a3gseT1+RPCeiXrnYADQ5sg8GFHeNP+0W17MxI5XwzoPonN9xFcJmWIblc=
            =siQN
            -----END PGP MESSAGE-----
          fp: A883B02E14B7EAF0A6BDAF69ECD23C5916E31D4F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.0
