apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: '^4.0.0-0'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 1m
  values:
    controller:
#      image:
#        tag: v1.0.0-beta.1
#        digest: sha256:f058f3fdc940095957695829745956c6acddcaef839907360965e27fd3348e2e
      extraArgs:
        enable-ssl-passthrough: ""
