apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: '3.23.0'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 1m
  values:
    tcp:
      2222: "deis/deis-builder:2222"
    controller:
      containerPort:
        http: 8082
        https: 9443
      hostNetwork: true
      hostPort:
        enabled: true
        ports:
          http: 8082
          https: 9443
      kind: DaemonSet
      service:
        type: NodePort
        ports:
          http: 8082
          https: 9443
