apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: example-cdk8s-ruby
  namespace: default
spec:
  interval: 1m
  url: https://github.com/kingdonb/example-cdk8s-ruby
  ref:
    branch: synths
