apiVersion: v1
data:
    GITHUB_TOKEN: ENC[AES256_GCM,data:mDpx5E3LnDn2Lo9eKV4QvN3UXSefKXyuUgmRN/SLZIv8ZTSIR44nGjbrCMmK3mpfk8GJVdA/jkQ=,iv:ngIWGEKAGlTL7n31EiTlGlqB5+JUvX6Gp5FU/SJ+ERM=,tag:xqDLiP8AZwhiJBmG5y/mCw==,type:str]
    GITHUB_USER: ENC[AES256_GCM,data:fdkLKjHXmLt9RAf6,iv:vGCXjXHLoqMQr0cCXmdgl3hBwCBhxa7X3cRGp11TJPo=,tag:ctxarifuTZVdr4rFDGEVTg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: github-token-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-03-29T17:41:03Z"
    mac: ENC[AES256_GCM,data:OlH6XQnbJD9bXvSPhdp8X0eBMjZKy+lB4lwl/E42YMCAD6mnT0kbxDJmxNOtgotXuSv80XlJEzNsnAgdHtlIMbpU4wMq4ligUAAJMk64gQ8oCIyCNOg1/mAScJQurdj/l6Og7B/7SWrRuzk5hDbdJPLSnS0/SsMZ8s6STWlniuU=,iv:QFwuaM+ja9oB66Q0/FNpqBT0GfbH2ZVPFYsfT8OcwZM=,tag:z2JJqmpju7hkBXQf/uROdA==,type:str]
    pgp:
        - created_at: "2021-03-29T17:41:02Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA06rSFOpPqRMARAAlQ0qgt97Y1FAZezTD6cuHxNTyEHfaeJCYqkbqnmG2qpX
            zFaadr3IA9dweQ1NDB6103LAiTsa8yCklX28Rav/gUNkuHjhj1btZ647EBZqCuEq
            5PiegYHD1Gxp9v2JT+TAhLHXbQ1+cMMs/qwsZFqLJCUH7pcEk1lkmpu1P9jeX/aD
            qURztX/6x9L/9c7WIJ3ikUsDiDjHt4PgOVDxTb2m9G2aqzYf9rn0Mnpnw4emCcY+
            iPJ/OcWgXIH0M0sFchrTZ0bHWyCXeUpoggfIiIfZhEr/X/fm2KEdYSvFLcuT1Ll5
            9b0GRT7w6QMHlw6wxtdiVtgYO4pEZiKKMQFr0YK653E+LTcHhKGnMwi3e1tm19zG
            wetosH2G3jsEgLsEl/iRSPPIVtMS8cUaOSBxehoxyvBut+PxqIaMbFRG0FgkNBEh
            2JIKxslViPMEosz4gIDL5CUy7KQ5gm+dY8hSkfA7vgrqRLQHO7ZFic43fZR1Ec58
            6sykwGKTNQgg0H5Cg9m1ip7/Fa9751NEc1fIczkrXeyPvigH1UDyrBPQckE31z0W
            FjATOZTMpAK9HL7Gw/8SX8UjAuYUq7PaXFnHIZuCL1uZJxtv181EEWkdaOdMxlnK
            8owvL6UYE/ANCIwd5kDjWkSF/rgXbGTELKWZ9f3lHCtvcfjFCRbKd+P11yt5l1HS
            XgEmxoDoDRhosj/Ax1szYFrTYHKtajRjfhhcuoObVh7Bdtq/lZEfpkKu9C60yR+/
            PCagqunw+8W6ygWln3GvedyVW87rsqY/UcfxnWAJsjrMRoeYgyuuC9vO31/OOyg=
            =Sl1H
            -----END PGP MESSAGE-----
          fp: A883B02E14B7EAF0A6BDAF69ECD23C5916E31D4F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.0
