apiVersion: v1
data:
    GITHUB_TOKEN: ENC[AES256_GCM,data:NUFdysoYJ4eFRjLAbHOsAjwCT4CLyrIk5+2KgehWx5cn6LsK+EM0Ef01VAb/gu/5A099MS9phZU=,iv:89F5LmqVK14Wge6TkkZMx4jUhSkdIj61TndK1ASLqzM=,tag:QB635fcDzSFEgmdDDD5MBw==,type:str]
    GITHUB_USER: ENC[AES256_GCM,data:tT5KS0bg/+hdvaXZ,iv:vxkoK82gCXaN0Dm4X60vZYR9agXaVtx19IpMPTQB8Q4=,tag:jSV5JaJR8nzgpSDJLxDwDQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: github-token-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-03-29T17:48:29Z"
    mac: ENC[AES256_GCM,data:24IjTuKaXnZlJTaQWHflE2IMzHD5xaII0RISuV4GH388TI922Achmd6SH1YKQoFSJxvfSRo1njlvAVcTfLKy9I1fIPKo6CwTn8qTv5J5Q1rSdUM0Jx5T67Gzu7tgf39rkklBfVS9xe+OH2I5hIKgox8RAfxGZTE+mHdyyNUsFPw=,iv:yVSTrtMPzQrRazzJTC7x+5NGBvfwJUL7hUrhiBMRcZA=,tag:S4mHxamBo96oW4PfGgsSHg==,type:str]
    pgp:
        - created_at: "2021-03-29T17:48:28Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA06rSFOpPqRMAQ//d0h1USxGw0Jk6IQBHgCYH57LTD78zk4IZwAPPJmLqoDT
            02OrYh+lakI+KlCOdpERIulg2L2Hj+8n6usnB9NC10H5fd0m5l+vMouYxLuM0cbj
            Aaa/FrrY2FzKVos0kE3fhCTKEi1zp/CpKoRoJCJcrd0AfNrRHLfpDK3lVVxU4lV5
            RUsYGV09BwBvkzboUbzn4687OSGcH2z4SZvcIFLDazdXUWgn5ml36DE2BNtXh28X
            AGskSfJ3egQyG30Zb2idIF8bhVp5R8t0Lu3tvzpQ3LHsyx2kC/n0ZEZtfT7oz54s
            suC6jQOZ8S53mXe4+HxjiBtoT1kId4WUwSlPnEsR1q/xYPlXY9jSxzfpuxdhmz2+
            kzN5mWQxnWZukTCrda5syNJxSoCafBlhlyEzo+xXKh5qRlyfDBFktuTrMWjMHGrj
            PRKzYhzCKi1bIHdgDS73dw1VZevSAMW+gyiZgLYT4D+v406qZkM7UhY1W0/nePJA
            N3LdplIP+F00AaEP7tj7yCl5xdsqv74ixQyuSNhfhzW/2xjOxYdbUVr+N4gpNNcS
            mBgi87yWrxO4niJWIuDqSArQbcN4L5ga+JO7CVFe5hXhOJHr5oCPOrVDzdghm9D5
            VMHHX13pXhofWmeRO1D6PSEEmkX3xQ3Ez0jviN5hcp3RKU2qvaIpqJIMUapXbUjS
            XgFshxKtI8IcIdDopkjLnYP/YRlboTbmPRXCUYW1zhwKbdN60oDgA4/j3dFTX7wO
            udnZCEPAVYMRVFRPY6vQhODgnSEvHcHbHnn8G5wrHFsKtjeAu4CzQtcLPruiKnI=
            =fgoX
            -----END PGP MESSAGE-----
          fp: A883B02E14B7EAF0A6BDAF69ECD23C5916E31D4F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.0
