apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: terminal
  namespace: flux-system
spec:
  suspend: false
  interval: 15m
  targetNamespace: default
  storageNamespace: default
  timeout: 10m
  chart:
    spec:
      chart: terminal
      version: '0.2'
      sourceRef:
        kind: GitRepository
        name: okteto-charts
        namespace: default
      interval: 15m
  values:
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"
