apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: terminal
  namespace: default
spec:
  interval: 15m
  targetNamespace: default
  storageNamespace: default
  timeout: 10m
  chart:
    spec:
      chart: terminal
      version: '0.3'
      sourceRef:
        kind: GitRepository
        name: okteto-charts
        namespace: default
      interval: 15m
  values:
    resources:
      requests:
        memory: "50Mi"
        cpu: "100m"
      limits:
        memory: "1Gi"
        cpu: "2"
    ingress:
      enabled: true
